version: "2.0"
networks:
  net:
volumes:
  uploads:
services:
  latex:
    image: aido93/latex-server
    build: .
    container_name: latex-server
    #environment:
    #  DEBUG: "false"
    ports:
      - 8082:8080
    networks:
      - net
    volumes:
      - uploads:/data
